# Generated by Django 4.0.4 on 2022-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='ticker',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
    ]
