# Generated by Django 4.0.4 on 2023-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_project_signed_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquiditymaker',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='56', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketmakingpool',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='56', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='56', max_length=100),
        ),
        migrations.AlterField(
            model_name='vault',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='56', max_length=100),
        ),
    ]
