# Generated by Django 4.0.4 on 2023-01-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_liquiditymaker_network_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='token',
        ),
        migrations.AddField(
            model_name='marketmakingpool',
            name='token',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
        migrations.AlterField(
            model_name='liquiditymaker',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketmakingpool',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='vault',
            name='network',
            field=models.CharField(choices=[('5', 'Goerli Test Network'), ('56', 'Binance Smart Chain')], default='5', max_length=100),
        ),
    ]
